/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myApp;

import java.util.ArrayList;
import java.util.Arrays;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    public void testFound() {
        int[] array1 = {1,2,3,4,5};
        assertTrue(App.checkIfMultipleOfIndex(array1, 4,1));
      }
  
      @Test
      public void testNotFound() {
        int[] array1 = {1,2,3,4,5};
        assertFalse(App.checkIfMultipleOfIndex(array1, 5,1));
      }
  
      @Test
      public void testEmptyArray() {
        int[] array1 = {};
        assertFalse(App.checkIfMultipleOfIndex(array1,1,1));
      }
  
      @Test
      public void testNull() {
        int[] array1 =null;
        assertFalse(App.checkIfMultipleOfIndex(array1, 1,1));
      }
  
}
