/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myApp;

public class App {
    public static boolean checkIfMultipleOfIndex(int array[],int number,int index) {
        if(array == null)
        {
            return false;
        }
        if(array.length == 0 )
        {
            return false;
        }
        if(array[index] % number == 0 )
            return true;
        
        return false;
    }

}
